/**
 * REPRODUCE — apaga derivados, re-roda pipeline, regrava lockfile.
 *
 * Run: bun scripts/reproduce.ts
 *
 * Determinístico: dado os MESMOS inputs (raw_trades.csv + b3/*.csv),
 * o output deve ser byte-a-byte idêntico → mesmo hash no lockfile.
 */

import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import {
  buildLockEntry,
  writeLockfile,
  type Lockfile,
} from "../src/market/reproducibility";

const ROOT = process.cwd();

const DERIVED = [
  { rel: "canonical/canonical_trade_log.json", kind: "canonical" },
  { rel: "canonical/canonical_metrics.json", kind: "canonical" },
  { rel: "canonical/canonical_parameters.json", kind: "canonical" },
  { rel: "canonical/canonical_metadata.json", kind: "canonical" },
  { rel: "canonical/raw_trades.sha256", kind: "canonical" },
  { rel: "market/manifests/datasets.json", kind: "market" },
];

function rm(rel: string): void {
  const abs = path.join(ROOT, rel);
  if (fs.existsSync(abs)) fs.unlinkSync(abs);
}

function run(cmd: string): void {
  console.log(`$ ${cmd}`);
  execSync(cmd, { stdio: "inherit", cwd: ROOT });
}

function main(): void {
  // Fix timestamps for determinism within a single reproduce run.
  if (!process.env.TITAN_FIXED_TS) {
    process.env.TITAN_FIXED_TS = "2026-01-01T00:00:00.000Z";
  }
  const env = `TITAN_FIXED_TS=${process.env.TITAN_FIXED_TS}`;

  for (const d of DERIVED) rm(d.rel);
  // Clear market hashes dir (regenerated by ingest-market).
  const hashesDir = path.join(ROOT, "market", "hashes");
  if (fs.existsSync(hashesDir)) {
    for (const f of fs.readdirSync(hashesDir)) {
      if (f.endsWith(".sha256")) fs.unlinkSync(path.join(hashesDir, f));
    }
  }

  run(`${env} bun scripts/derive-canonical.ts`);
  run(`${env} bun scripts/ingest-market.ts`);

  const entries = DERIVED
    .filter((d) => fs.existsSync(path.join(ROOT, d.rel)))
    .map((d) => buildLockEntry(d.rel, d.kind));

  const lock: Lockfile = {
    version: 1,
    generatedAt: process.env.TITAN_FIXED_TS!,
    entries,
  };
  writeLockfile(lock);
  console.log(`[reproduce] OK — lockfile written with ${entries.length} entries.`);
}

main();
